spring:
  profiles:
    active: prod
# https://stackoverflow.com/questions/70036953/springboot-2-6-0-spring-fox-3-failed-to-start-bean-documentationpluginsboot
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

generator:
  protected-group: default,renren-fast,jdbc-template,jpa,ui,jpa-starp,util,beetlsql,common-mapper,mybatis,mybatis-plus