server:
  port: 30306
# 自定义swagger配置信息
swagger:
  title: 程の代码生成器
  description: 一键生成前后端所有代码
  version: 1.0.0

freemarker:
  # freemarker 模板文件夹路径
  templates-path: /opt/service/code-generator/templates
  # 已删除的模板组文件夹存放目录
  deleted-path: /opt/service/code-generator/deleted
